import { useState, useEffect, useRef } from 'react'
import { motion } from 'framer-motion'
import { ChevronRight } from 'lucide-react'

const LAST_UPDATED = 'May 20, 2026'

const SECTIONS = [
  {
    id: 'acceptance',
    title: '1. Acceptance of Terms',
    content: `By accessing or using CyberCli Chat ("the Service"), operated by CyberMindCLI ("we," "us," or "our"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, you may not access or use the Service. These Terms constitute a legally binding agreement between you and CyberMindCLI.

By creating an account, you represent that you are at least 13 years of age (or the minimum age of digital consent in your jurisdiction), have the legal capacity to enter into binding contracts, and will comply with all applicable laws and regulations. If you are accessing the Service on behalf of an organization, you represent that you have authority to bind that organization to these Terms.`,
  },
  {
    id: 'description',
    title: '2. Description of Service',
    content: `CyberCli Chat is an AI-powered chat platform that provides access to multiple large language models (LLMs) from third-party providers including but not limited to OpenRouter, Google Gemini, Groq, Cerebras, Cloudflare, HuggingFace, Bytez, and NVIDIA. The Service includes:

• Multi-model AI chat with intelligent routing
• Council Mode for multi-model consensus responses
• Text-to-speech and voice input capabilities
• Conversation history and organization features
• API access for programmatic integration
• Additional features as added over time

CyberMindCLI reserves the right to modify, suspend, or discontinue any aspect of the Service at any time, with or without notice. We will make reasonable efforts to notify users of significant changes that materially affect their use of the Service.`,
  },
  {
    id: 'accounts',
    title: '3. User Accounts',
    content: `To access certain features of the Service, you must create an account. You are responsible for:

**Account Security**: Maintaining the confidentiality of your login credentials. You must immediately notify us at security@cybermindcli.com of any unauthorized use of your account. We are not liable for losses arising from unauthorized account access resulting from your failure to protect your credentials.

**Account Accuracy**: Providing accurate, current, and complete information during registration. You agree to promptly update your account information to keep it accurate, current, and complete.

**Account Activity**: All activity that occurs under your account, whether or not you authorized it. You may not share your account credentials with third parties, sell or transfer your account, or create accounts by automated means.

**Prohibited Accounts**: You may not create an account if you have been previously banned from the Service, or if you are located in a jurisdiction subject to international sanctions that would prohibit your use of the Service.`,
  },
  {
    id: 'acceptable-use',
    title: '4. Acceptable Use Policy',
    content: `You agree not to use the Service to generate, transmit, or facilitate:

**Prohibited Content**: Child sexual abuse material (CSAM) or any content that sexualizes minors; content that constitutes illegal harassment, threats, or incitement to violence; materials that violate intellectual property rights of third parties; defamatory content that you know to be false and damaging.

**Security Violations**: Unauthorized penetration testing against third-party systems without explicit written authorization; development of malware designed to cause harm to third-party systems; circumvention of security measures of any system without authorization.

**Spam and Manipulation**: Automated generation of spam content; coordinated inauthentic behavior campaigns; creation of synthetic media designed to deceive (deepfakes) in harmful contexts.

**Legal Violations**: Any use that violates applicable local, national, or international laws or regulations; export control violations; sanctions violations.

We reserve the right to suspend or terminate accounts that violate this policy, and to report illegal activity to appropriate law enforcement authorities.`,
  },
  {
    id: 'intellectual-property',
    title: '5. Intellectual Property',
    content: `**Your Content**: You retain ownership of all content you input into the Service ("User Content"). By using the Service, you grant CyberMindCLI a limited, non-exclusive, worldwide, royalty-free license to process, transmit, and store your User Content solely for the purpose of providing the Service.

**AI Outputs**: Outputs generated by AI models in response to your prompts ("AI Outputs") are not guaranteed to be original and may be similar to outputs generated for other users. We make no claims of copyright ownership in AI Outputs, and our ability to grant you rights in AI Outputs is limited by the terms of the underlying model providers.

**Service IP**: The Service, including its software, design, features, and documentation, is owned by CyberMindCLI and protected by intellectual property laws. You may not copy, modify, distribute, sell, or lease any part of the Service.

**Feedback**: Any feedback, suggestions, or ideas you provide about the Service may be used by CyberMindCLI without compensation or attribution to you.`,
  },
  {
    id: 'privacy',
    title: '6. Privacy and Data',
    content: `Your use of the Service is also governed by our Privacy Policy, which is incorporated into these Terms by reference. Key data practices include:

• Conversation data is stored encrypted in MongoDB Atlas with field-level encryption for sensitive fields
• We do not train our models on your conversation data without explicit consent
• Authentication data is managed by Supabase with industry-standard security practices
• We implement data minimization principles — we collect only what is necessary to provide the Service
• You may request deletion of your account and associated data at any time by contacting privacy@cybermindcli.com

For complete information about how we handle your data, please review our Privacy Policy and GDPR Notice.`,
  },
  {
    id: 'disclaimers',
    title: '7. Disclaimers and Limitations',
    content: `**AI Accuracy**: AI-generated content may be inaccurate, incomplete, or outdated. The Service is not a substitute for professional legal, medical, financial, or security advice. You assume sole responsibility for evaluating the accuracy of AI Outputs and for any reliance you place on them.

**Service Availability**: The Service is provided "as is" and "as available" without warranties of any kind, express or implied. We do not warrant that the Service will be uninterrupted, error-free, or free of viruses or other harmful components.

**Limitation of Liability**: To the maximum extent permitted by applicable law, CyberMindCLI shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data, or goodwill, arising from your use of or inability to use the Service.

**Third-Party Models**: We act as a gateway to third-party AI model providers. The outputs of those models are governed by the terms of those providers, and we disclaim all liability for the content generated by third-party models.`,
  },
  {
    id: 'termination',
    title: '8. Termination',
    content: `**By You**: You may terminate your account at any time by accessing your account settings and requesting account deletion. Upon termination, your right to use the Service will immediately cease.

**By Us**: We may suspend or terminate your account immediately, without prior notice or liability, for any reason including: violation of these Terms; illegal use of the Service; non-payment of applicable fees; or inactivity for more than 24 months.

**Effect of Termination**: Upon termination, we will delete your account data in accordance with our data retention policy. Conversations and settings will be permanently deleted within 30 days of termination. Some aggregate, anonymized data may be retained for analytics purposes.`,
  },
  {
    id: 'governing-law',
    title: '9. Governing Law & Disputes',
    content: `These Terms are governed by and construed in accordance with applicable laws. Any disputes arising from these Terms or your use of the Service shall be resolved through binding arbitration, except that either party may seek injunctive relief in a court of competent jurisdiction to prevent irreparable harm.

If you are an EU/EEA consumer, mandatory local consumer protection laws may apply and may not be waived by these Terms. Nothing in these Terms limits any rights you have under applicable consumer protection legislation.

**Class Action Waiver**: To the extent permitted by law, you agree to resolve disputes with us only on an individual basis and not as part of a class action.`,
  },
  {
    id: 'changes',
    title: '10. Changes to Terms',
    content: `We reserve the right to modify these Terms at any time. We will provide at least 30 days' notice before material changes take effect by: sending an email to your registered address, displaying a prominent notice in the Service interface, and updating the "Last Updated" date on this page.

Your continued use of the Service after changes take effect constitutes acceptance of the revised Terms. If you do not agree to the revised Terms, you must stop using the Service.

For questions about these Terms, contact us at legal@cybermindcli.com.`,
  },
]

function LegalSidebar({ sections, activeId }) {
  return (
    <aside className="sticky top-24 hidden lg:block w-64 flex-shrink-0">
      <div className="rounded-2xl border border-white/[0.06] bg-[#0D0D14] p-5">
        <p className="text-xs font-semibold text-[#6B7280] uppercase tracking-widest mb-4">Contents</p>
        <nav className="space-y-1">
          {sections.map((s) => (
            <a
              key={s.id}
              href={`#${s.id}`}
              className={`flex items-center gap-2 text-xs py-1.5 px-2 rounded-lg transition-all duration-200 leading-snug ${
                activeId === s.id
                  ? 'text-white bg-violet-500/10 border-l-2 border-violet-500 pl-3'
                  : 'text-[#6B7280] hover:text-white hover:bg-white/[0.03]'
              }`}
            >
              <ChevronRight className={`w-3 h-3 flex-shrink-0 transition-colors ${activeId === s.id ? 'text-violet-400' : 'text-[#374151]'}`} />
              {s.title}
            </a>
          ))}
        </nav>
      </div>
    </aside>
  )
}

function useSectionTracker(sections) {
  const [activeId, setActiveId] = useState(sections[0]?.id)

  useEffect(() => {
    const handler = () => {
      const scrollPos = window.scrollY + 120
      let current = sections[0]?.id
      for (const s of sections) {
        const el = document.getElementById(s.id)
        if (el && el.offsetTop <= scrollPos) current = s.id
      }
      setActiveId(current)
    }
    window.addEventListener('scroll', handler, { passive: true })
    return () => window.removeEventListener('scroll', handler)
  }, [sections])

  return activeId
}

function formatContent(text) {
  const parts = text.split(/(\*\*[^*]+\*\*)/g)
  return parts.map((part, i) => {
    if (part.startsWith('**') && part.endsWith('**')) {
      return <strong key={i} className="text-white font-semibold">{part.slice(2, -2)}</strong>
    }
    return <span key={i}>{part}</span>
  })
}

export default function TermsPage() {
  const activeId = useSectionTracker(SECTIONS)

  return (
    <div className="pt-28 pb-20 bg-[#0A0A0F]">
      <div className="section-padding">
        <div className="container-custom">
          {/* Header */}
          <div className="mb-12">
            <span className="text-xs font-semibold text-accent tracking-widest uppercase mb-4 block">Legal</span>
            <h1 className="text-3xl md:text-4xl font-extrabold text-white mb-3">Terms of Service</h1>
            <p className="text-sm text-[#6B7280]">Last updated: {LAST_UPDATED} · Effective immediately</p>
          </div>

          <div className="flex gap-12 items-start">
            <LegalSidebar sections={SECTIONS} activeId={activeId} />

            {/* Main content */}
            <main className="flex-1 min-w-0">
              <div className="rounded-2xl border border-white/[0.06] bg-[#0D0D14] p-8 mb-6">
                <p className="text-[#9CA3AF] text-sm leading-relaxed">
                  Please read these Terms of Service carefully before using CyberCli Chat. These Terms govern your access to and use of the Service. By using the Service, you agree to these Terms. If you have questions, contact us at <a href="mailto:legal@cybermindcli.com" className="text-violet-400 hover:text-violet-300">legal@cybermindcli.com</a>.
                </p>
              </div>

              <div className="space-y-10">
                {SECTIONS.map((section, i) => (
                  <motion.section
                    key={section.id}
                    id={section.id}
                    initial={{ opacity: 0, y: 20 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true, margin: '-80px' }}
                    transition={{ duration: 0.5, delay: 0 }}
                    className="scroll-mt-24"
                  >
                    <h2 className="text-xl font-bold text-white mb-4 pb-3 border-b border-white/[0.06]">
                      {section.title}
                    </h2>
                    <div className="space-y-4">
                      {section.content.split('\n\n').map((para, j) => (
                        para.startsWith('• ') ? (
                          <ul key={j} className="space-y-2 pl-2">
                            {para.split('\n').map((item, k) => (
                              <li key={k} className="flex items-start gap-2 text-sm text-[#9CA3AF] leading-relaxed">
                                <span className="text-violet-400 flex-shrink-0 mt-0.5">•</span>
                                <span>{formatContent(item.replace('• ', ''))}</span>
                              </li>
                            ))}
                          </ul>
                        ) : (
                          <p key={j} className="text-sm text-[#9CA3AF] leading-[1.8]">
                            {formatContent(para)}
                          </p>
                        )
                      ))}
                    </div>
                  </motion.section>
                ))}
              </div>

              <div className="mt-12 p-6 rounded-xl border border-white/[0.06] bg-white/[0.02]">
                <p className="text-xs text-[#6B7280] leading-relaxed">
                  These Terms of Service were last updated on {LAST_UPDATED} and supersede all previous versions.
                  For legal inquiries, contact <a href="mailto:legal@cybermindcli.com" className="text-violet-400">legal@cybermindcli.com</a>.
                </p>
              </div>
            </main>
          </div>
        </div>
      </div>
    </div>
  )
}
